#!/bin/bash 

DebuggerEnabled=false

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color


constructDebugger() {
  DebuggerEnabled=true
}

error() {

  if [[ "$DebuggerEnabled" != "true" ]] ; then 
    return 
  fi

  echo -e $RED $@ $NC 
}


warning() {

  if [[ "$DebuggerEnabled" != "true" ]] ; then 
    return 
  fi

  echo -e $YELLOW $@ $NC 
}


debug() {

  if [[ "$DebuggerEnabled" != "true" ]] ; then 
    return 
  fi

  echo -e $GREEN $@ $NC 
}

destructDebugger() {
  unset DebuggerEnabled
  unset RED 
  unset GREEN
  unset YELLOW
  unset NC 
  unset -f constructDebugger
  unset -f error
  unset -f warning
  unset -f debug
  unset -f destructDebugger
}
