#!/usr/bin/expect -f

set USERNAME [lindex $argv 0]
set KEY [lindex $argv 1]

spawn bash -c "git push"

expect "Username for 'https://github.com': "
send "$USERNAME\n"

expect "Password for 'https://$USERNAME@github.com':"
send -- "$KEY\n"

interact
