#!/bin/bash

GITPUSHSCRIPTPATH="$( cd -- "$(dirname "$0")" >/dev/null 2>&1 ; pwd -P )"

push() { 

  if [[ $# != 1 ]] 
  then
    echo ""
    echo "Create a aliase in keys file : $GITPUSHSCRIPTPATH/keys"
    echo "With username and key seperated by space and pass that variable name to this file"
    echo "For Ex : ' aliase dummy=\"username gitKey\" '"
    echo "Then pass aliase to push like : ' push dummy ' "
    echo ""
    return -1
  fi

  eval "source $GITPUSHSCRIPTPATH/keys"

  args=($(eval "echo \$$1"))

  if [[ "${#args[@]}" != "2" ]] ; then
    echo "Either \"$1\" doesn't exist or malformed"
  fi

  if [[ $(which expect) == "expect not found" ]] ;
  then 
    echo "Install \"expect\" to use this function"
    return -1
  fi

  eval "expect $GITPUSHSCRIPTPATH/expect ${args[1]} ${args[2]}"

}
